# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: up

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  repository_dispatch:
    types: up
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: update
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git clone https://gitee.com/lxk0301/jd_scripts.git scripts
          cd scripts
          git checkout master
          git add .
          git commit -m "update" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          directory: scripts
          branch: master
          force: true