# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: up

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  repository_dispatch:
    types: up
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: update
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git remote set-url origin https://gitee.com/lxk0301/jd_scripts.git
          git fetch origin master
          git reset --hard origin/master
          git pull origin master
          sed -ri "s/\('\\\x47\\\x49\\\x54\\\x48\\\x55\\\x42'\)/('GxIxTxHxUxB')/g" jdCookie.js
          git add .
          git commit -m "update" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
          force: true